#!/usr/bin/env node
// challenge.js — argue against a note using the user's own prior notes.
// Usage: challenge.js <slug-or-path>
//
// The forum's "challenge, don't absorb" principle: feed the target note + a few
// related vault notes to Haiku with a refute-prompt, then append a `## Challenge`
// section to the note. Never overwrites existing content; does NOT flip verified.

const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const { spawnSync } = require("node:child_process");

const SKILL_LIB = path.join(os.homedir(), ".claude", "skills", "sb", "lib");
const { VAULT, EXCLUDE_FOLDERS } = require(path.join(SKILL_LIB, "vault.js"));
const { parseFrontmatter } = require(path.join(SKILL_LIB, "markdown.js"));

const MODEL = process.env.SB_ANALYZER_MODEL || "claude-haiku-4-5-20251001";
const CLAUDE_BIN = process.env.SB_CLAUDE_BIN || "claude";

const target = process.argv.slice(2).find((a) => !a.startsWith("--"));
if (!target) { console.error("Usage: challenge.js <slug-or-path>"); process.exit(2); }

const file = resolveNote(target);
if (!file) { console.error(`No note found matching "${target}".`); process.exit(1); }

const raw = fs.readFileSync(file, "utf8");
const { meta, body } = parseFrontmatter(raw);
const related = gatherRelated(meta, file).slice(0, 5);

const prompt = `You are a skeptical reviewer. Argue AGAINST the claims in the note below, using the user's own related notes as ammunition where relevant. Be specific and concrete: name the weakest assumption, the edge cases where it fails, contradicting evidence, and what would have to be true for it to be wrong. Do not be agreeable. 4-8 bullet points.

Return PLAIN MARKDOWN bullets only (no preamble, no fences).

## NOTE UNDER CHALLENGE
${body.slice(0, 12000)}

## RELATED NOTES (context)
${related.map((r) => `### ${r.name}\n${r.excerpt}`).join("\n\n").slice(0, 20000)}`;

const r = spawnSync(CLAUDE_BIN, ["-p", "--model", MODEL, "--output-format", "text"], {
  input: prompt, encoding: "utf8", maxBuffer: 20 * 1024 * 1024,
});
if (r.status !== 0) { console.error(`claude -p failed: ${r.stderr || r.status}`); process.exit(1); }

const date = new Date().toISOString().slice(0, 10);
const section = `\n\n## Challenge (${date})\n> Generated by ${MODEL} — a devil's-advocate pass, not ground truth.\n\n${r.stdout.trim()}\n`;
fs.appendFileSync(file, section);
console.log(`Appended challenge to ${path.relative(VAULT, file)}.`);

function gatherRelated(meta, self) {
  const out = [];
  const tags = new Set((meta.tags || []).map((t) => String(t).toLowerCase().replace(/^#/, "")));
  (function walk(dir) {
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      if (e.name.startsWith(".") || EXCLUDE_FOLDERS.includes(e.name)) continue;
      const full = path.join(dir, e.name);
      if (e.isDirectory()) walk(full);
      else if (e.name.endsWith(".md") && full !== self) {
        try {
          const { meta: m, body } = parseFrontmatter(fs.readFileSync(full, "utf8"));
          const mt = new Set((m.tags || []).map((t) => String(t).toLowerCase().replace(/^#/, "")));
          if ([...mt].some((t) => tags.has(t))) {
            out.push({ name: path.basename(full, ".md"), excerpt: body.slice(0, 500) });
          }
        } catch {}
      }
    }
  })(VAULT);
  return out;
}

function resolveNote(t) {
  if (t.endsWith(".md") && fs.existsSync(t)) return path.resolve(t);
  const want = t.replace(/\.md$/, "").toLowerCase();
  let found = null;
  (function walk(dir) {
    if (found) return;
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      if (found) return;
      if (e.name.startsWith(".") || EXCLUDE_FOLDERS.includes(e.name)) continue;
      const full = path.join(dir, e.name);
      if (e.isDirectory()) walk(full);
      else if (e.name.endsWith(".md") && path.basename(e.name, ".md").toLowerCase() === want) found = full;
    }
  })(VAULT);
  return found;
}
