#!/usr/bin/env node
// init.js — (re)generate the vault's machine-facing entry docs, idempotently.
// Usage: init.js
//
// Writes two files at the vault root:
//   _CLAUDE.md — the folder map, note types, AI-first + verified rules, and the
//                full /sb: command list (what future-Claude reads first).
//   index.md   — per-folder note counts, entry points, and Base view links.
//
// Both files bound their generated region with <!-- @sb-generated:start/end -->
// sentinels; only that region is rewritten, so any hand-added notes outside the
// sentinels survive re-runs. Called standalone or by /sb:consolidate.

const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");

const SKILL_LIB = path.join(__dirname, "..", "..", "lib");
const SKILL_ROOT = path.join(os.homedir(), ".claude", "skills", "sb");
const { VAULT, DIR, TYPE_MAP } = require(path.join(SKILL_LIB, "vault.js"));

const START = "<!-- @sb-generated:start -->";
const END = "<!-- @sb-generated:end -->";

const claudeFile = path.join(VAULT, "_CLAUDE.md");
const indexFile = path.join(VAULT, "index.md");

writeGenerated(claudeFile, buildClaude());
writeGenerated(indexFile, buildIndex());

console.log(`Wrote ${path.relative(VAULT, claudeFile)} and ${path.relative(VAULT, indexFile)} (idempotent, sentinel-bounded).`);

// ---------------------------------------------------------------------------

// Replace only the region between the sentinels; preserve everything else. If the
// file has no sentinels yet (or does not exist), create it with the region.
function writeGenerated(file, region) {
  const block = `${START}\n${region.trimEnd()}\n${END}\n`;
  let content;
  if (fs.existsSync(file)) {
    const cur = fs.readFileSync(file, "utf8");
    if (cur.includes(START) && cur.includes(END)) {
      content = cur.replace(new RegExp(`${esc(START)}[\\s\\S]*?${esc(END)}\\n?`), block);
    } else {
      content = cur.trimEnd() + "\n\n" + block;
    }
  } else {
    content = block;
  }
  fs.writeFileSync(file, content);
}

function buildClaude() {
  const L = [];
  L.push("---");
  L.push("type: vault-guide");
  L.push(`date: ${today()}`);
  L.push("tags: [meta, guide]");
  L.push("ai-first: true");
  L.push("---");
  L.push("");
  L.push("## For future Claude");
  L.push("This is the ai-mind second-brain vault. Read this file first: it maps the");
  L.push("folders, the note types, the trust rules, and the /sb: commands. Notes here");
  L.push("are written for you to reason over, not for human review.");
  L.push("");
  L.push("# ai-mind — vault guide");
  L.push("");
  L.push("## Folder map");
  for (const [key, folder] of numberedFolders()) {
    L.push(`- \`${folder}/\` — ${folderPurpose(key)}`);
  }
  L.push("");
  L.push("## Note types");
  const types = [...new Set(Object.values(TYPE_MAP))].sort();
  L.push(types.map((t) => `\`${t}\``).join(", "));
  L.push("");
  L.push("## Rules (AI-first + verified)");
  L.push("- Every first-class note carries frontmatter (`type`, `tags`, `date`, `ai-first: true`) and a `## For future Claude` preamble.");
  L.push("- ASCII only — no smart quotes / em-dashes (the write-time validator warns).");
  L.push("- AI-drafted notes are `verified: false` with a visible `[!ai]` callout; they appear in `unverified.base` until `/sb:verify` flips them. Never let an unverified draft harden into fact.");
  L.push("- Facts that change over time are recorded bi-temporally (a `timeline:` list) — never overwritten.");
  L.push("");
  L.push("## Commands");
  for (const c of listCommands()) L.push(`- \`/${c.name}\` — ${c.desc}`);
  L.push("");
  return L.join("\n");
}

function buildIndex() {
  const L = [];
  L.push("---");
  L.push("type: vault-index");
  L.push(`date: ${today()}`);
  L.push("tags: [meta, index]");
  L.push("ai-first: true");
  L.push("---");
  L.push("");
  L.push("## For future Claude");
  L.push("Live index of the vault: note counts per folder, entry points, and Base");
  L.push("views. Regenerated by /sb:init (and /sb:consolidate).");
  L.push("");
  L.push("# Vault index");
  L.push("");
  L.push("## Counts");
  for (const [key, folder] of numberedFolders()) {
    const n = countMd(path.join(VAULT, folder));
    L.push(`- \`${folder}/\` — ${n} note(s)`);
  }
  L.push("");
  L.push("## Entry points");
  L.push("- [[Home]] — dashboard homepage (`00_Dashboard/Home.md`)");
  L.push("- [[_CLAUDE]] — vault guide for future-Claude");
  L.push("- `05_Tasks/INDEX.md` — all open tasks across projects");
  L.push("");
  L.push("## Base views (`00_Dashboard/`)");
  const bases = listBases();
  if (bases.length) for (const b of bases) L.push(`- \`${DIR.dashboard}/${b}\``);
  else L.push("- _(none yet — run /sb:bases)_");
  L.push("");
  return L.join("\n");
}

function numberedFolders() {
  // DIR entries whose folder name has a NN_ numeric prefix, ordered by that number.
  return Object.entries(DIR)
    .filter(([, folder]) => /^\d\d_/.test(folder))
    .sort((a, b) => a[1].localeCompare(b[1]));
}

function folderPurpose(key) {
  const P = {
    dashboard: "homepage, Base views, tag index",
    conversations: "auto-captured Claude Code conversations, scoped by project",
    projects: "per-project INDEX / kanban / lessons / plans / decisions / journal / reviews",
    lessons: "reusable lessons learned",
    topics: "study / reference topic notes",
    tasks: "global task INDEX (per-project tasks live under 02_Projects/<slug>)",
    connections: "cross-note MOC-style connection notes",
    reviews: "daily / weekly review notes",
    insights: "synthesis, distillation, and recurring-theme notes",
    exports: "generated exports (graphs, etc.)",
    memory: "mirror of the harness file-memory facts",
    decisions: "architecture decision records (ADRs)",
    people: "people / CRM notes with interaction logs",
    meetings: "meeting notes (attendees auto-linked to People)",
    zettel: "atomic permanent Zettelkasten notes",
    habits: "habit tracker notes with streaks",
    ideas: "captured ideas awaiting graduation into projects",
    inbox: "unfiled scratch / reports",
  };
  return P[key] || key;
}

function listCommands() {
  const dir = path.join(SKILL_ROOT, "commands");
  const out = [];
  let files;
  try { files = fs.readdirSync(dir).filter((f) => f.endsWith(".md")).sort(); } catch { return out; }
  for (const f of files) {
    try {
      const txt = fs.readFileSync(path.join(dir, f), "utf8");
      const name = (txt.match(/^name:\s*(.+)$/m) || [])[1] || `sb:${path.basename(f, ".md")}`;
      let desc = (txt.match(/^description:\s*(.+)$/m) || [])[1] || "";
      desc = desc.replace(/\s+/g, " ").slice(0, 100);
      out.push({ name: name.trim(), desc: desc.trim() });
    } catch {}
  }
  return out;
}

function listBases() {
  try {
    return fs.readdirSync(path.join(VAULT, DIR.dashboard)).filter((f) => f.endsWith(".base")).sort();
  } catch { return []; }
}

function countMd(dir) {
  let n = 0;
  const stack = [dir];
  while (stack.length) {
    const d = stack.pop();
    let ents; try { ents = fs.readdirSync(d, { withFileTypes: true }); } catch { continue; }
    for (const e of ents) {
      if (e.name.startsWith(".") || e.name === "_archive") continue;
      const full = path.join(d, e.name);
      if (e.isDirectory()) stack.push(full);
      else if (e.name.endsWith(".md")) n++;
    }
  }
  return n;
}

function today() { return new Date().toISOString().slice(0, 10); }
function esc(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
